name: qw_web
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_qrcode_scanner: ^1.1.1
  qrcode_reader_web: ^1.1.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^5.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true




  #
